# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: SUSTech1K
  dataset_root: your_path
  dataset_partition: ./datasets/SUSTech1K/SUSTech1K.json
  num_workers: 4
  data_in_use: None
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: SUSTech1K

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 120000
  save_name: GaitGL
  eval_func: evaluate_indoor_dataset
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: BaseSilCuttingTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128]
  class_num: 250

optimizer_cfg:
  lr: 1.0e-3
  momentum: 0.9
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 30000
    - 90000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: 
  sync_BN: true
  total_iter: 120000
  sampler:
    batch_shuffle: true
    batch_size:
      - 8
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
    
